---
title: "epmr Package Overview"
author: "Tony Albano"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{epmr Package Overview}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

The `epmr` package supports educational and psychological measurement in R, with methods and example data for psychometric analysis of results from standardized tests and assessments. This vignette summarizes the main features of the package. For a thorough demonstration, see the associated book at [https://thetaminusb.com/intro-measurement-r/](https://thetaminusb.com/intro-measurement-r/).

## Overview

The `epmr` package is organized by type of analysis. Here's a list of the main functions, which all have the suffix `study` after an abbreviation of the type of analysis in the first few letters.

* `astudy` is for examining interrater agreement via percentage agreement, kappa, and weighted kappa statistics.  
* `difstudy` reports differential item functioning results for a set of items.  
* `dstudy` returns descriptive statistics for one or more variables in a data frame.  
* `fastudy` is a simple wrapper for exploratory factor analysis with `factanal`.  
* `gstudy` runs generalizability studies using multilevel modeling with the `lme4` package.  
* `irtstudy` currently runs the Rasch item reponse theory model using the `lme4` package.  
* `ostudy` is for option analysis, also called distractor analysis, with unscored, multiple choice item response data.  
* `rstudy` estimates tau-equivalent and congeneric reliability, also called coefficients alpha and omega, as well as standard error of measurement.  

Helper functions are also provided for  

* plotting results from item response theory modeling using `ggplot2` with `irtplot`  
* rescaling variables to have a certain range, mean, and standard deviation with `setmin`, `setmax`, `setmean`, and `setsd`
* recoding variables with `rescore`, formerly named `recode` which conflicted with the `dplyr` function by the same name.  

## Data

The data in `epmr` come from two studies involving testing data.

* `PISA09` is a data frame containing demographic, cognitive, and noncognitive variables for a subset of students participating in the 2009 administration of the Programme for International Student Assessment (PISA).  
* `BDI` is a list containing the correlation matrix, covariance matrix, and variable labels for an administration of the Beck Depression Inventory II, as reported in a research study by Whisman, Perez, and Ramel (see the help file for reference).  
